### PR TITLE
added private and cert extraction

### PR DESCRIPTION
**Pull request by fariouche**
Just a small PR that add private key and certificate extraction, in separate files (suffixed .key and .crt, in PEM format)

### CODE REVIEW

**Comment by neykov** [comment]
That's a nifty change @fariouche. Can you share an example use case for this functionality?
Is the key getting logged just once? Would multiple writes of the key break the formatting?

**Comment by fariouche** [comment]
In don't touch the current file (that is for wireshark)... However, I dump the key and certs in <path to secrets log file>.key and <path to secrets log file>.crt (in PEM format)
Nothing special needs to be specified, it will automatically dump them if found.
And yes, multiple keys will be appended (same for certs)

In my case, it dumped one key, and the full certificate chain (and it worked like a charm)

I'm not a java programmer, so if you need me to rename or refactor a bit, let me know

**Comment by neykov** [comment]
Hi @fariouche. I played with the changes for a while - can you help me understand why this would be a useful feature?
If you are able to attach to a server process, you should already be able to access the configuration files of the process, the private key and certificate in particular.

**Comment by fariouche** [comment]
In my case, the private key and certificate were hidden somewhere and it was much easier to extract them instead of searching/decompiling the java. (but maybe there is an easy way to do it that I don't know?)

**Comment by neykov** [comment]
OK, I'll merge the PR. I'll later update some parts of it - I'd still like to preserve 1.6 compatibility at the very least.
Can you resolve the mege conflicts.

**Comment by fariouche** [comment]
Done! Thanks!

**Comment by neykov** [comment]
Thank you for the contribution @fariouche!

**Pull request merged**
