### PR TITLE
fix getJarFile NPE while -javaagent in some applications.

### PR DESCRIPTION
**Pull request by fishjam**
when I try to use it with `-javaagent` in some applications, it will error with NPE. 
So I fixed it. please check

### CODE REVIEW

**Comment by neykov** [comment]
Hi @fishjam. Thank you for the contribution. Happy to merge it.
Can you share a set up that triggers this code path?

**Comment by fishjam** [comment]
you can try it in idea.

**Comment by neykov** [comment]
> you can try it in idea.

I mean how should I set up my environment so that I get a null value for `clz.getProtectionDomain().getCodeSource().getLocation();`?

**Comment by fishjam** [comment]
you can install idea, and add following command in `idea64.exe.vmoptions`  ( change path according your env), and start idea, then you can found the NPE. 
```
-javaagent:E:\CodeIdeaCheck\extract-tls-secrets\target\extract-tls-secrets-4.1.0-SNAPSHOT.jar=extract-tls-wireshark.txt
```

**Comment by neykov** [comment]
Got it, haven't realised you are instrumenting Idea itself.

**Pull request merged**
